version: '3.3'
services:
  node1:
    build: ""
    cap_add:
      - ALL
    command: bitcoind -regtest -server -addnode=10.7.0.12:12345 -addnode=10.7.0.13:12345 -addnode=10.7.0.14:12345 -rpcuser=rpc -rpcpassword=xxx -rpcport=10340  --datadir=/root/bitcoind-simnet/ -port=12345
    networks:
      vpcbr:
        ipv4_address: 10.7.0.11
  node2:
    build: ""
    cap_add:
      - ALL
    command: bitcoind -regtest -server -addnode=10.7.0.11:12345 -addnode=10.7.0.13:12345 -addnode=10.7.0.14:12345 -rpcuser=rpc -rpcpassword=xxx -rpcport=10340  --datadir=/root/bitcoind-simnet/ -port=12345
    networks:
      vpcbr:
        ipv4_address: 10.7.0.12
  node3:
    build: ""
    cap_add:
      - ALL
    command: bitcoind -regtest -server -addnode=10.7.0.12:12345 -addnode=10.7.0.11:12345 -addnode=10.7.0.14:12345 -rpcuser=rpc -rpcpassword=xxx -rpcport=10340  --datadir=/root/bitcoind-simnet/ -port=12345
    networks:
      vpcbr:
        ipv4_address: 10.7.0.13
  node4:
    build: ""
    cap_add:
      - ALL
    command: bitcoind -regtest -server -addnode=10.7.0.11:12345 -addnode=10.7.0.13:12345 -addnode=10.7.0.12:12345 -rpcuser=rpc -rpcpassword=xxx -rpcport=10340  --datadir=/root/bitcoind-simnet/ -port=12345
    networks:
      vpcbr:
        ipv4_address: 10.7.0.14
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.0.0/16