version: "3.3"
services:
  bitcoind-node:
    container_name: bitcoind-node
    image: kylemanna/bitcoind
    restart: always
    expose:
      - "8332"
      - "18332"
    ports:
      - "8333:8333"
      - "127.0.0.1:8332:8332"
      - "127.0.0.1:18332:18332"
    volumes:
      - ./data/btc/test/coind:/bitcoin/.bitcoin
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf